# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SingleSectionTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SingleSectionTableView

  pod 'SnapKit'

  target 'SingleSectionTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SingleSectionTableViewUITests' do
    # Pods for testing
  end

end
